language: cpp
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq libncurses-dev doxygen graphviz libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev
compiler:
 - clang
 - gcc
install:
 - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - clang
script:
 - make
 - ./test
